import type { Metadata } from 'next';
import './globals.css';
import { SparklesCore } from '@/components/SparklesCore';

export const metadata: Metadata = {
  title: 'Neurify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-custom antialiased">
        <div className="relative w-full min-h-screen bg-slate-950 overflow-hidden">
          {/* Particle effect in the background */}
          <div className="fixed inset-0 w-full h-screen md:block hidden">
            {/* Particles for larger screens (tablet and desktop) */}
            <SparklesCore
              id="tsparticlesdesktop"
              background="transparent"
              minSize={1}
              maxSize={2}
              particleDensity={40}
              className="w-full h-full"
              particleColor="#FFFFFF"
              speed={0.75}
            />
          </div>
          {/* Main content */}
          <div className="relative z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
